### ISSUE TITLE
tags without flow

### ISSUE THREAD

**Issue by jrochkind** [technicalpickles/capistrano-gitflow#2]
Am I correct that this is the correct repo for current release of capistrano-gitflow?

I am interested in the git tagging functionality, but actually don't want to use or force a multiple stage staging/production workflow at this point.  (I like having the option for the future)

Rather, I'd like my cap recipe to automatically add a tag on every deploy, and to allow deploying of a tag named on the command line -- but not force deploy first to staging then to production, and not assume/take over the cap `set :branch` behavior, but just use the actually configured branch. 

Your code seems to have covered a bunch of edge cases and gotchas with what I _do_ want to do, though. 

Are you interested in potentially this gem being modified to be flexible and allow what I want to do? Or should I just fork it to make something that does what I want to do instead?  If you are interested in a pull request, any thoughts on the 'right' way to allow both behaviors?

**Comment by bogdanRada** [comment]
@technicalpickles. This also seems to be stale for almost 4 years. Any thoughts on this? I could take a stab at it if you could give me your thoughts about this.

**Comment by technicalpickles** [comment]
@bogdanRada it could be useful, but there hasn't been any others interested (based on comments). Allowing both might get tricky and introduce some complexity, which would be the downside.

**Comment by bogdanRada** [comment]
Yes i think you're right. I have been looking through to other projects and seems someone already had the initiative and implemented capistrano-deploytags which adds a tag for every deploy to every stage which seems to be what the OP asked for. I believe we could close this since implementing something similar don't think will help anyone and will only bring more maintenance burden . what do you think?
